fin-diary-war/src/java/web/CategoryController.java
package web;

import api.CategoryManager;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.faces.convert.Converter;
import javax.inject.Inject;
import javax.inject.Named;
import model.Category;

/**
 *
 * @author Veronika Vasinova
 */
@RequestScoped
@Named("category")
public class CategoryController implements Serializable {

    @EJB
    CategoryManager catManager;

    @Inject
    ActiveSession user;

    private boolean insertAction = false;
    private String categoryName;
    private Category category;

    /**
     * Returns all categories created by specific user.
     *
     * @return list of all user's Categories
     */
    public List<Category> show() {
        return catManager.getCategories(user.getUser());
    }

    /**
     * Deletes the selected category.
     *
     * @param category select category
     * @return path to reload page
     */
    public String delete(Category category) {
        catManager.deleteCategory(category);
        return "categories";
    }

    /**
     * Saves values do db after submit form.
     *
     * @return path to previous page
     */
    public String saveForm() {
        if (insertAction) {
            catManager.addCategory(user.getUser(), categoryName);
        } else {
            catManager.updateName(category, categoryName);
        }
        return "categories";
    }

    /**
     * Converts strings to {@link Category} and {@link Category} to strings as
     * required.
     *
     * @return converter
     */
    public Converter getCategoryConverter() {
        return catManager.getCategoryConverter(user.getUser());
    }

    /**
     * Redirects the user to the page to edit category.
     *
     * @param c select category
     * @return destination where the user would be redirected after click
     */
    public String edit(Category c) {
        this.category = c;
        this.categoryName = c.getName();
        return "category-edit";
    }

    /**
     * Redirects the user to teh page to add category.
     *
     * @return destination where the user would be redirected after click
     */
    public String insert() {
        insertAction = true;
        return "category-edit";
    }

    public String getCategoryName() {
        return categoryName;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    public boolean isInsertAction() {
        return insertAction;
    }

    public void setInsertAction(boolean insertAction) {
        this.insertAction = insertAction;
    }

    public Category getCategory() {
        return category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

}

fin-diary-war/src/java/web/RecordController.java
package web;

import api.RecordManager;
import api.RecordTypeManager;
import api.WalletManager;
import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;

import javax.faces.convert.Converter;
import javax.inject.Inject;
import javax.inject.Named;
import model.Category;
import model.Record;
import model.RecordType;
import model.Wallet;
import util.DatePicker;

/**
 *
 * @author Veronika
 */
@SessionScoped
@Named("record")
public class RecordController implements Serializable {

    @EJB
    RecordManager manager;

    @EJB
    WalletManager walletManager;

    @EJB
    RecordTypeManager typeManager;

    @Inject
    ActiveSession user;

    private boolean insertAction = false;
    private Record record;

    private Wallet selectedWallet;
    private Category selectedCategory;
    private Date selectedDateFrom;
    private Date selectedDateTo;

    private Wallet wallet;
    private Category category;
    private double value;
    private Date date;
    private String note;
    private RecordType type;

    public RecordController() {
    }

    /**
     * Redirects the user to the page to add record.
     *
     * @return destination where the user would be redirected
     */
    public String insert() {
        clearForm();
        insertAction = true;
        return "record-edit";
    }

    /**
     * Returns all record filtered by wallet, category, date from and date to.
     *
     * @return list of selected records
     */
    public List<Record> getRecords() {
        if (selectedWallet != null || selectedCategory != null || selectedDateFrom != null || selectedDateTo != null) {
            return manager.getWalletRecords(selectedWallet,
                    selectedCategory,
                    selectedDateFrom,
                    selectedDateTo);
        } else {
            return manager.getUserRecords(user.getUser());

        }
    }

    /**
     * Deletes the selected record.
     *
     * @param r select record
     * @return path to reload page
     */
    public String delete(Record r) {
        manager.deleteRecord(r);
        clearForm();
        return "records";
    }

    /**
     * Saves values do db after submit insert/edit form.
     *
     * @return path to previous page
     */
    public String saveForm() {
        if (insertAction) {
            manager.addRecord(wallet, category, value, date, note, type);
        } else {
            record.setNote(note);
            record.setValue(value);
            record.setCategory(category);
            record.setDate(date);
            record.setOperation(type);
            manager.updateRecord(record);
        }
        clearForm();
        return "records";
    }

    private void clearForm() {
        insertAction = false;
        this.record = null;
        this.category = null;
        this.type = null;
        this.wallet = null;
        this.note = "";
        this.value = 0;
        this.date = new Date();
    }

    /**
     * Redirects the user to the page to edit selected record.
     *
     * @param r selected record category
     * @return destination where the user would be redirected after click
     */
    public String edit(Record r) {
        this.record = r;
        this.category = r.getCategory();
        this.value = r.getValue();
        this.date = r.getDate();
        this.type = r.getOperation();
        this.wallet = r.getWallet();
        this.note = r.getNote();
        return "record-edit";
    }

    /**
     * Sets the initial values for the filter - date from, date to and wallet.
     */
    @PostConstruct
    public void init() {
        selectedDateFrom = DatePicker.getMinDate();
        selectedDateTo = DatePicker.getMaxDate();
        List<Wallet> wallets = walletManager.getUserWallets(user.getUser());
        if (!wallets.isEmpty()) {
            selectedWallet = wallets.get(0);
        }

    }

    /**
     * Converts strings to {@link Record} and {@link Record} to strings as
     * required.
     *
     * @return converter
     */
    public Converter getRecordConverter() {
        return manager.getRecordsConverter();
    }

    /**
     * Converts strings to {@link RecordType} and {@link RecordType} to strings
     * as required.
     *
     * @return converter
     */
    public Converter getRecordTypeConverter() {
        return typeManager.getTypeConverter();
    }

    /**
     * Returns all record types.
     *
     * @return list of recor types
     */
    public List<RecordType> getRecordTypes() {
        return typeManager.getRecordTypes();
    }

    public boolean isInsertAction() {
        return insertAction;
    }

    public void setInsertAction(boolean insertAction) {
        this.insertAction = insertAction;
    }

    public Record getRecord() {
        return record;
    }

    public void setRecord(Record record) {
        this.record = record;
    }

    public Wallet getWallet() {
        return wallet;
    }

    public void setWallet(Wallet wallet) {
        this.wallet = wallet;
    }

    public Category getCategory() {
        return category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    public double getValue() {
        return value;
    }

    public void setValue(double value) {
        this.value = value;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public RecordType getType() {
        return type;
    }

    public void setType(RecordType type) {
        this.type = type;
    }

    public Wallet getSelectedWallet() {
        return selectedWallet;
    }

    public void setSelectedWallet(Wallet selectedWallet) {
        this.selectedWallet = selectedWallet;
    }

    public Category getSelectedCategory() {
        return selectedCategory;
    }

    public void setSelectedCategory(Category selectedCategory) {
        this.selectedCategory = selectedCategory;
    }

    public Date getSelectedDateFrom() {
        return selectedDateFrom;
    }

    public void setSelectedDateFrom(Date selectedDateFrom) {
        this.selectedDateFrom = selectedDateFrom;
    }

    public Date getSelectedDateTo() {
        return selectedDateTo;
    }

    public void setSelectedDateTo(Date selectedDateTo) {
        this.selectedDateTo = selectedDateTo;
    }

}

fin-diary-war/src/java/web/SummaryController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package web;

import api.RecordManager;
import api.WalletManager;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;
import model.Category;
import model.Wallet;
import util.DatePicker;

@SessionScoped
@Named("summary")
public class SummaryController implements Serializable {

    private Date dateFrom;
    private Date dateTo;
    private Wallet selectWallet;
    private Category selectCategory;
    
    private boolean generate = false;

    @EJB
    WalletManager walletManager;

    @EJB
    RecordManager recordManager;

    @Inject
    ActiveSession user;

    public SummaryController() {

    }

    private List<Wallet> getWallets() {
        return walletManager.getUserWallets(user.getUser());
    }

    public List<Category> getCategories() {
        if (selectCategory == null) {
            return walletManager.getWalletCategories(selectWallet);
        } else {
            List<Category> category = new ArrayList<>();
            category.add(selectCategory);
            return category;
        }
    }

    public Map<Category, List<Double>> getCategoriesSummary() {
        
        return recordManager.getCategoriesSummary(getCategories(), selectWallet, dateFrom, dateTo);
    }

    public double walletBalanceByCategory() {
        return walletManager.getWalletBalanceByCategory(getCategories(), selectWallet, dateFrom, dateTo);
    }
    
    
    public double getIncome(){
        return walletManager.getWalletIncome(getCategories(), selectWallet, dateFrom, dateTo);
    }
    
    public double getExpenses(){
        return walletManager.getWalletExpenses(getCategories(), selectWallet, dateFrom, dateTo);
    }
    
    public double getListSum(List<Double> list) {
        return list.stream().mapToDouble(Double::doubleValue).sum();
    }

    @PostConstruct
    public void init() {
        dateFrom = DatePicker.getMinDate();
        dateTo = DatePicker.getMaxDate();
        if(!getWallets().isEmpty())
            selectWallet = getWallets().get(0);
       
    }

    public Date getDateFrom() {
        return dateFrom;
    }

    public void setDateFrom(Date dateFrom) {
        this.dateFrom = dateFrom;
    }

    public Date getDateTo() {
        return dateTo;
    }

    public void setDateTo(Date dateTo) {
        this.dateTo = dateTo;
    }

    public Wallet getSelectWallet() {
        return selectWallet;
    }

    public void setSelectWallet(Wallet selectWallet) {
        this.selectWallet = selectWallet;
    }

    public Category getSelectCategory() {
        return selectCategory;
    }

    public void setSelectCategory(Category selectCategory) {
        this.selectCategory = selectCategory;
    }

    public boolean isGenerate() {
        return generate;
    }

    public void setGenerate(boolean generate) {
        this.generate = generate;
    }
    
    

}

fin-diary-war/src/java/web/WalletController.java
package web;

import api.CurrencyManager;
import api.WalletManager;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.faces.convert.Converter;
import javax.inject.Inject;
import javax.inject.Named;
import model.Currency;
import model.Wallet;

@RequestScoped
@Named("wallet")
public class WalletController implements Serializable {

    @EJB
    private WalletManager manager;

    @EJB
    CurrencyManager currencyManager;

    @Inject
    ActiveSession user;

    private boolean insertAction = false;
    private String name;
    private double balance;
    private Currency currency;

    private Wallet wallet;

    public WalletController() {
    }

    ;
    
    /**
     * Returns all wallets created by specific user.
     *
     * @return list of all user's wallets
     */
    public List<Wallet> getWallets() {
        return manager.getUserWallets(user.getUser());
    }

    /**
     * Deletes the selected wallet.
     *
     * @param wallet selected wallet
     * @return path to reload page
     */
    public String delete(Wallet wallet) {
        manager.deleteWallet(wallet);
        return "wallets";
    }

    /**
     * Saves values do db after submit form.
     *
     * @return path to previous page
     */
    public String saveForm() {
        if (insertAction) {
            manager.addWallet(user.getUser(), name, currency, balance);
        } else {
            manager.renameWallet(wallet, name);
        }
        return "wallets";
    }

    /**
     * Redirects the user to the page to edit wallet.
     *
     * @param wallet selected category
     * @return destination where the user would be redirected after click
     */
    public String edit(Wallet wallet) {
        this.wallet = wallet;
        this.balance = wallet.getBalance();
        this.currency = wallet.getCurrency();
        this.name = wallet.getName();
        return "wallet-edit";
    }

    /**
     * Redirects the user to the page to add wallet.
     *
     * @return destination where the user would be redirected after click
     */
    public String insert() {
        insertAction = true;
        return "wallet-edit";
    }

    /**
     * Converts strings to {@link Currency} and {@link Currency} to strings as
     * required.
     *
     * @return converter
     */
    public Converter getCurrencyConverter() {
        return currencyManager.getCurrencyConverter();
    }

    /**
     * Returns all currencies in db.
     *
     * @return list of all currencies
     */
    public List<Currency> getCurrencies() {
        return currencyManager.getCurrencies();
    }

    /**
     * Converts strings to {@link Wallet} and {@link Wallet} to strings as
     * required.
     *
     * @return converter
     */
    public Converter getWalletConverter() {
        return manager.getWalletConverter(user.getUser());
    }

    public boolean isInsertAction() {
        return insertAction;
    }

    public void setInsertAction(boolean insertAction) {
        this.insertAction = insertAction;
    }

    public Wallet getWallet() {
        return wallet;
    }

    public void setWallet(Wallet wallet) {
        this.wallet = wallet;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public double getBalance() {
        return balance;
    }

    public void setBalance(double balance) {
        this.balance = balance;
    }

    public Currency getCurrency() {
        return currency;
    }

    public void setCurrency(Currency currency) {
        this.currency = currency;
    }

}

fin-diary-war/web/categories.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>

<ui:composition template="./templates/master-template.xhtml" xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:hc = "http://java.sun.com/jsf/composite/components">
    <ui:define name="top">
        <ui:include src="./templates/page-header.xhtml "/>
    </ui:define>

    <ui:define name="content">
        <hc:headerComponent headerLabel="Kategorie" insertAction="#{category.insert()}"/>
        <h:form>
            <h:dataTable styleClass="table" value="#{category.show()}" var="c">
                <h:column>
                    <f:facet name="header">Název</f:facet>
                        #{c.name}
                </h:column>

                <h:column>
                    <f:facet name="header">Akce</f:facet>
                    <h:commandLink class="btn btn-danger btn-circle"  
                                   onclick="if (!deleteRow('Opravdu chcete smazat kategorii #{c.name} a s ní všechny záznamy?'))
                                               return false;"
                                   action="#{category.delete(c)}">
                        <img src="resources/img/ic_delete.svg" alt="delete" />
                    </h:commandLink>
                    <h:commandLink class="btn btn-info btn-circle" 
                                   action="#{category.edit(c)}">
                        <img src="resources/img/ic_edit.svg" alt="edit" />
                    </h:commandLink>
                </h:column>
            </h:dataTable>
        </h:form>


    </ui:define>

</ui:composition>

fin-diary-war/web/category-edit.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>

<ui:composition template="./templates/master-template.xhtml" xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
                xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
                xmlns:sc = "http://java.sun.com/jsf/composite/components">
    <ui:define name="top">
        <ui:include src="./templates/page-header.xhtml "/>
    </ui:define>

    <ui:define name="content">
        <h:form class="form-edit">   
            <h:inputHidden id="cat" value="#{category.category}" converter="#{category.categoryConverter}" />
            <h:inputHidden id="insertAction" value="#{category.insertAction}" />

            <c:if test="#{category.insertAction}">
                <h2>Přidání kategorie</h2>
            </c:if>

            <c:if test="#{not category.insertAction}">
                <h2>Úprava kategorie</h2>
            </c:if>

            <h:outputLabel for="categoryName">Název</h:outputLabel>
            <h:inputText id="categoryName" class="form-control" value="#{category.categoryName}" pt:required="required" />

            <sc:saveComponent goBack="categories.xhtml" saveAction="#{category.saveForm()}" />

        </h:form>
    </ui:define>            
</ui:composition>

fin-diary-war/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>
        <link href="https://fonts.googleapis.com/css?family=Shadows+Into+Light+Two" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" />
        <h:outputStylesheet name="welcome.css" library="css"></h:outputStylesheet>
        <title>Finanční deník</title>
    </h:head>
    <h:body>
        <div class="container text-center">
            <h1>MŮJ FINANČNÍ DENÍK</h1>
            <img src="https://upload.wikimedia.org/wikipedia/commons/6/60/Circle-icons-money.svg" class="img-responsive" width="400" height="300" alt="Money" />
            <h4 class="text-center text-justify">Zaznamenejte každý svůj provedený výdaj nebo příjem a mějte tak k dispozici užitečný nástroj, díky kterému neztratíte přehled o svých financích.</h4>

            <div class="row center">
                <div class="col-md-6"><a href="login.xhtml" class="btn btn-light btn-lg btn-margin" role="button">Přihlásit se</a></div>
                <div class="col-md-6"><a href="register.xhtml" class="btn btn-light btn-lg btn-margin" role="button">Vytvořit účet</a></div>
            </div>        

        </div>
    </h:body>
</html>

fin-diary-war/web/record-edit.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>

<ui:composition template="./templates/master-template.xhtml" xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:t="http://xmlns.jcp.org/jsf/passthrough"
                xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
                xmlns:sc = "http://java.sun.com/jsf/composite/components">
    <ui:define name="top">
        <ui:include src="./templates/page-header.xhtml "/>
    </ui:define>

    <ui:define name="content">
        <h:form class="form-edit">   
            <h:inputHidden id="cat" value="#{record.record}" converter="#{record.recordConverter}" />
            <h:inputHidden id="insertAction" value="#{record.insertAction}" />

            <c:if test="#{record.insertAction}">
                <h2>Přidání záznamu</h2>
            </c:if>

            <c:if test="#{not record.insertAction}">
                <h2>Úprava záznamu</h2>

            </c:if>

            <h:outputLabel for="note">Název</h:outputLabel>
            <h:inputText t:type="text" id="note" class="form-control" value="#{record.note}"  />

            <h:outputLabel for="value">Částka</h:outputLabel>
            <h:inputText t:type="number" t:min="1" id="value" class="form-control" value="#{record.value}" t:required="required" />

            <h:outputLabel for="date">Datum</h:outputLabel>
            <h:inputText t:type="date" id="date" class="form-control" value="#{record.date}" t:required="required" >

                <f:convertDateTime pattern="yyyy-MM-dd"/>  
            </h:inputText>

            <h:outputLabel rendered="#{record.insertAction}" for="wallet">Peněženka</h:outputLabel>

            <h:selectOneMenu id="wallet" rendered="#{record.insertAction}" class="form-control" value="#{record.wallet}" converter="#{wallet.getWalletConverter()}" t:required="required">
                <f:selectItems value="#{wallet.wallets}" var="cust" itemLabel="#{cust.name}"  />
            </h:selectOneMenu>



            <h:outputLabel for="category">Kategorie</h:outputLabel>
            <h:selectOneMenu id="category" class="form-control" value="#{record.category}" converter="#{category.categoryConverter}" t:required="required">
                <f:selectItems value="#{category.show()}" var="cust" itemLabel="#{cust.name}"  />
            </h:selectOneMenu>

            <h:outputLabel for="type">Typ</h:outputLabel>
            <h:selectOneMenu id="type" class="form-control" value="#{record.type}" converter="#{record.recordTypeConverter}" t:required="required">
                <f:selectItems value="#{record.recordTypes}" var="c" itemLabel="#{c.name}"  />
            </h:selectOneMenu>

            <sc:saveComponent goBack="records.xhtml" saveAction="#{record.saveForm()}" />
        </h:form>

    </ui:define>            
</ui:composition>

fin-diary-war/web/summary.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>

<ui:composition template="./templates/master-template.xhtml" xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:hc = "http://java.sun.com/jsf/composite/components"
                xmlns:t="http://xmlns.jcp.org/jsf/passthrough"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <ui:define name="top">
        <ui:include src="./templates/page-header.xhtml "/>
    </ui:define>

    <!-- bezny obsah -->
    <ui:define name="content"  >

        <hc:headerComponent headerLabel="Přehled" insertAction="#{todo}" showAddButton="false" />
        <h:form>

            
            <hc:filterComponent selectCategory="#{summary.selectCategory}"
                                selectWallet="#{summary.selectWallet}"
                                selectDateFrom="#{summary.dateFrom}"
                                selectDateTo="#{summary.dateTo}"
                                table="myTable"/>

            <div class="row" style="margin-top: 20px;">
                <div class="col-md-6">
                    <div class="myTable">
                        <h5 class="text-center" style="padding: 10px 0 10px 0;">#{summary.selectWallet.name}</h5>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Kategorie</th>
                                    <th>Výdaje</th>
                                    <th>Příjmy</th>
                                    <th>Bilance</th>
                                </tr>
                            </thead>
                            <ui:repeat value="#{summary.categoriesSummary.entrySet().toArray()}" var="entry">
                                <tr>
                                    <td>#{entry.key.name}</td>
                                    <ui:repeat value="#{entry.value}" var="r">
                                        <td>#{r} #{summary.selectWallet.currency.code}</td>
                                    </ui:repeat>
                                    <td>#{summary.getListSum(entry.value)} #{summary.selectWallet.currency.code}</td>
                                </tr>
                            </ui:repeat>
                            <tr  style="border-top: 2px solid black">
                                <td></td>
                                <td></td>
                                <td>Celkem:</td>
                                <td>#{summary.walletBalanceByCategory()} #{summary.selectWallet.currency.code}</td>
                            </tr>

                        </table>

                    </div>
                </div>
                <div class="col-md-6">
                    <div id="chart"></div>
                    <h:outputScript rendered="true">
                        google.charts.load('current', {'packages':['corechart']});
                        google.charts.setOnLoadCallback(drawChart);

                        // Draw the chart and set the chart values
                        function drawChart() {
                        var data = google.visualization.arrayToDataTable([
                        ['Task', 'Hours per Day'],
                        ['Příjmy', #{summary.income}],
                        ['Výdaje', #{summary.expenses}]
                        ]);

                        // Optional; add a title and set the width and height of the chart
                        var options = {};


                        var chart = new google.visualization.PieChart(document.getElementById('chart'));
                        chart.draw(data, options);
                        }
                    </h:outputScript>

                </div>


            </div>


        </h:form>
    </ui:define>
</ui:composition>

fin-diary-war/web/wallet-edit.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<ui:composition template="./templates/master-template.xhtml" xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
                xmlns:sc = "http://java.sun.com/jsf/composite/components"
                xmlns:jsf="http://java.sun.com/jsf" >
    <ui:define name="top">
        <ui:include src="./templates/page-header.xhtml "/>
    </ui:define>

    <ui:define name="content">
        <h:form class="form-edit"> 
            <h:inputHidden id="wallet" value="#{wallet.wallet}" converter="#{wallet.walletConverter}" />
            <h:inputHidden id="insertAction" value="#{wallet.insertAction}" />

            <c:if test="#{wallet.insertAction}">
                <h2>Přidání peněženky</h2>
            </c:if>

            <c:if test="#{not wallet.insertAction}">
                <h2>Úprava peněženky</h2>
            </c:if>

            <h:outputLabel for="name">Název</h:outputLabel>
            <h:inputText id="name" class="form-control" value="#{wallet.name}"  pt:required="required" />

            <h:outputLabel for="balance" rendered="#{wallet.insertAction}">Zůstatek</h:outputLabel>

            <h:inputText id="balance" class="form-control" 
                         value="#{wallet.balance}" 
                         pt:required="required"  
                         pt:type="number"
                         rendered="#{wallet.insertAction}"/>

            <h:outputLabel for="currency">Měna</h:outputLabel>
            <h:selectOneMenu id="currency" class="form-control" value="#{wallet.currency}" converter="#{wallet.currencyConverter}">
                <f:selectItems value="#{wallet.currencies}" var="cust" itemLabel="#{cust.code}"  />
            </h:selectOneMenu>

            <sc:saveComponent goBack="wallets.xhtml" saveAction="#{wallet.saveForm()}" />

        </h:form>

    </ui:define>            




</ui:composition>